#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

rm -rf 0
touch 1.foam
cp -r 0wall 0

# runApplication blockMesh
# runApplication pisoFoam

runApplication blockMesh

# runApplication decomposePar
# runParallel pisoFoam

runApplication pisoFoam

#------------------------------------------------------------------------------